# /usr/local/bin/docker-compose -f /docs/dev-ops/environment/environment-docker-compose-2.4.yml up -d
# docker-compose -f docker-compose-app.yml up -d
# 你需要修改system为你自身系统的仓库名
services:
  s-pay-mall-ddd:
    image: yygqzzk/s-pay-mall-ddd-app:1.0-SNAPSHOT
    container_name: s-pay-mall-ddd
    restart: on-failure
    ports:
      - "8080:8080"
    environment:
      - TZ=PRC
      - SERVER_PORT=8080
    volumes:
      - ./log:/data/log
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - s-pay-mall

networks:
  s-pay-mall:
    external: true
